// ============================================================
// Static seed data — 300+ well-known players, no API needed
// ============================================================

export interface SeedClub {
  id: number
  name: string
  logo: string
  country: string
}

export interface SeedPlayer {
  id: number
  name: string
  photo: string
  nationality: string
  age: number
  position: 'Goalkeeper' | 'Defender' | 'Midfielder' | 'Attacker'
  clubIds: number[]  // most recent first
}

const IMG = (id: number) => `https://media.api-sports.io/football/players/${id}.png`
const LOGO = (id: number) => `https://media.api-sports.io/football/teams/${id}.png`

export const CLUBS: SeedClub[] = [
  // England
  { id: 33,  name: 'Manchester United', logo: LOGO(33),  country: 'England' },
  { id: 34,  name: 'Newcastle',         logo: LOGO(34),  country: 'England' },
  { id: 35,  name: 'Bournemouth',       logo: LOGO(35),  country: 'England' },
  { id: 36,  name: 'Fulham',            logo: LOGO(36),  country: 'England' },
  { id: 39,  name: 'Wolves',            logo: LOGO(39),  country: 'England' },
  { id: 40,  name: 'Liverpool',         logo: LOGO(40),  country: 'England' },
  { id: 41,  name: 'Southampton',       logo: LOGO(41),  country: 'England' },
  { id: 42,  name: 'Arsenal',           logo: LOGO(42),  country: 'England' },
  { id: 45,  name: 'Everton',           logo: LOGO(45),  country: 'England' },
  { id: 46,  name: 'Leicester',         logo: LOGO(46),  country: 'England' },
  { id: 47,  name: 'Tottenham',         logo: LOGO(47),  country: 'England' },
  { id: 48,  name: 'West Ham',          logo: LOGO(48),  country: 'England' },
  { id: 49,  name: 'Chelsea',           logo: LOGO(49),  country: 'England' },
  { id: 50,  name: 'Manchester City',   logo: LOGO(50),  country: 'England' },
  { id: 51,  name: 'Brighton',          logo: LOGO(51),  country: 'England' },
  { id: 52,  name: 'Crystal Palace',    logo: LOGO(52),  country: 'England' },
  { id: 55,  name: 'Brentford',         logo: LOGO(55),  country: 'England' },
  { id: 62,  name: 'Aston Villa',       logo: LOGO(62),  country: 'England' },
  // Spain
  { id: 73,  name: 'Atletico Madrid',   logo: LOGO(73),  country: 'Spain' },
  { id: 529, name: 'Barcelona',         logo: LOGO(529), country: 'Spain' },
  { id: 530, name: 'Atletico Madrid',   logo: LOGO(530), country: 'Spain' },
  { id: 532, name: 'Valencia',          logo: LOGO(532), country: 'Spain' },
  { id: 533, name: 'Villarreal',        logo: LOGO(533), country: 'Spain' },
  { id: 536, name: 'Sevilla',           logo: LOGO(536), country: 'Spain' },
  { id: 541, name: 'Real Madrid',       logo: LOGO(541), country: 'Spain' },
  { id: 543, name: 'Real Betis',        logo: LOGO(543), country: 'Spain' },
  { id: 548, name: 'Real Sociedad',     logo: LOGO(548), country: 'Spain' },
  // Germany
  { id: 157, name: 'Bayern Munich',     logo: LOGO(157), country: 'Germany' },
  { id: 159, name: 'Hertha Berlin',     logo: LOGO(159), country: 'Germany' },
  { id: 160, name: 'SC Freiburg',       logo: LOGO(160), country: 'Germany' },
  { id: 161, name: 'Union Berlin',      logo: LOGO(161), country: 'Germany' },
  { id: 162, name: 'Werder Bremen',     logo: LOGO(162), country: 'Germany' },
  { id: 163, name: 'Borussia M\'gladbach', logo: LOGO(163), country: 'Germany' },
  { id: 165, name: 'Borussia Dortmund', logo: LOGO(165), country: 'Germany' },
  { id: 167, name: 'RB Leipzig',        logo: LOGO(167), country: 'Germany' },
  { id: 168, name: 'Bayer Leverkusen',  logo: LOGO(168), country: 'Germany' },
  { id: 170, name: 'Eintracht Frankfurt', logo: LOGO(170), country: 'Germany' },
  // Italy
  { id: 487, name: 'Lazio',             logo: LOGO(487), country: 'Italy' },
  { id: 488, name: 'Roma',              logo: LOGO(488), country: 'Italy' },
  { id: 489, name: 'AC Milan',          logo: LOGO(489), country: 'Italy' },
  { id: 490, name: 'Atalanta',          logo: LOGO(490), country: 'Italy' },
  { id: 492, name: 'Napoli',            logo: LOGO(492), country: 'Italy' },
  { id: 494, name: 'Udinese',           logo: LOGO(494), country: 'Italy' },
  { id: 496, name: 'Juventus',          logo: LOGO(496), country: 'Italy' },
  { id: 497, name: 'Fiorentina',        logo: LOGO(497), country: 'Italy' },
  { id: 505, name: 'Inter Milan',       logo: LOGO(505), country: 'Italy' },
  // France
  { id: 79,  name: 'Lille',             logo: LOGO(79),  country: 'France' },
  { id: 80,  name: 'Lyon',              logo: LOGO(80),  country: 'France' },
  { id: 81,  name: 'Marseille',         logo: LOGO(81),  country: 'France' },
  { id: 82,  name: 'Monaco',            logo: LOGO(82),  country: 'France' },
  { id: 85,  name: 'Paris SG',          logo: LOGO(85),  country: 'France' },
  // Portugal
  { id: 211, name: 'Benfica',           logo: LOGO(211), country: 'Portugal' },
  { id: 212, name: 'Porto',             logo: LOGO(212), country: 'Portugal' },
  { id: 228, name: 'Sporting CP',       logo: LOGO(228), country: 'Portugal' },
  // Netherlands
  { id: 194, name: 'Ajax',              logo: LOGO(194), country: 'Netherlands' },
  { id: 197, name: 'PSV',               logo: LOGO(197), country: 'Netherlands' },
  // Other
  { id: 726, name: 'Al Nassr',          logo: LOGO(726), country: 'Saudi Arabia' },
  { id: 9580,name: 'Inter Miami',       logo: LOGO(9580),country: 'USA' },
  { id: 734, name: 'Al Hilal',          logo: LOGO(734), country: 'Saudi Arabia' },
]

export const PLAYERS: SeedPlayer[] = [
  // ── Attackers ────────────────────────────────────────────────────────────
  { id: 154,   name: 'Lionel Messi',           photo: IMG(154),   nationality: 'Argentina',    age: 36, position: 'Attacker',   clubIds: [9580, 85, 529] },
  { id: 874,   name: 'Cristiano Ronaldo',       photo: IMG(874),   nationality: 'Portugal',     age: 39, position: 'Attacker',   clubIds: [726, 33, 541, 49, 40] },
  { id: 278,   name: 'Kylian Mbappé',           photo: IMG(278),   nationality: 'France',       age: 25, position: 'Attacker',   clubIds: [541, 85, 82] },
  { id: 1100,  name: 'Erling Haaland',          photo: IMG(1100),  nationality: 'Norway',       age: 23, position: 'Attacker',   clubIds: [50, 165, 162] },
  { id: 47232, name: 'Vinicius Jr',             photo: IMG(47232), nationality: 'Brazil',       age: 23, position: 'Attacker',   clubIds: [541] },
  { id: 1090,  name: 'Harry Kane',              photo: IMG(1090),  nationality: 'England',      age: 30, position: 'Attacker',   clubIds: [157, 47] },
  { id: 306,   name: 'Mohamed Salah',           photo: IMG(306),   nationality: 'Egypt',        age: 31, position: 'Attacker',   clubIds: [40, 49, 489, 36] },
  { id: 80,    name: 'Antoine Griezmann',       photo: IMG(80),    nationality: 'France',       age: 32, position: 'Attacker',   clubIds: [73, 529, 73, 533] },
  { id: 276,   name: 'Neymar Jr',               photo: IMG(276),   nationality: 'Brazil',       age: 32, position: 'Attacker',   clubIds: [734, 85, 529] },
  { id: 303,   name: 'Roberto Firmino',         photo: IMG(303),   nationality: 'Brazil',       age: 32, position: 'Attacker',   clubIds: [726, 40, 162] },
  { id: 282,   name: 'Son Heung-min',           photo: IMG(282),   nationality: 'South Korea',  age: 31, position: 'Attacker',   clubIds: [47, 168, 165] },
  { id: 19220, name: 'Lamine Yamal',            photo: IMG(19220), nationality: 'Spain',        age: 17, position: 'Attacker',   clubIds: [529] },
  { id: 521,   name: 'Romelu Lukaku',           photo: IMG(521),   nationality: 'Belgium',      age: 30, position: 'Attacker',   clubIds: [505, 49, 33, 488] },
  { id: 184,   name: 'Karim Benzema',           photo: IMG(184),   nationality: 'France',       age: 36, position: 'Attacker',   clubIds: [541, 80] },
  { id: 2295,  name: 'Marcus Rashford',         photo: IMG(2295),  nationality: 'England',      age: 26, position: 'Attacker',   clubIds: [33, 62] },
  { id: 521,   name: 'Gabriel Martinelli',      photo: IMG(521),   nationality: 'Brazil',       age: 22, position: 'Attacker',   clubIds: [42] },
  { id: 1245,  name: 'Ousmane Dembélé',         photo: IMG(1245),  nationality: 'France',       age: 27, position: 'Attacker',   clubIds: [85, 529, 165] },
  { id: 2931,  name: 'Bukayo Saka',             photo: IMG(2931),  nationality: 'England',      age: 22, position: 'Attacker',   clubIds: [42] },
  { id: 17844, name: 'Rodrygo',                 photo: IMG(17844), nationality: 'Brazil',       age: 23, position: 'Attacker',   clubIds: [541] },
  { id: 301,   name: 'Luis Suárez',             photo: IMG(301),   nationality: 'Uruguay',      age: 37, position: 'Attacker',   clubIds: [529, 40, 496] },
  { id: 642,   name: 'Sadio Mané',              photo: IMG(642),   nationality: 'Senegal',      age: 32, position: 'Attacker',   clubIds: [157, 40, 41] },
  { id: 1911,  name: 'Richarlison',             photo: IMG(1911),  nationality: 'Brazil',       age: 26, position: 'Attacker',   clubIds: [47, 45, 51] },
  { id: 521,   name: 'Lautaro Martínez',        photo: IMG(521),   nationality: 'Argentina',    age: 26, position: 'Attacker',   clubIds: [505] },
  { id: 1485,  name: 'Ciro Immobile',           photo: IMG(1485),  nationality: 'Italy',        age: 33, position: 'Attacker',   clubIds: [487, 165] },
  { id: 521,   name: 'Olivier Giroud',          photo: IMG(521),   nationality: 'France',       age: 37, position: 'Attacker',   clubIds: [489, 49, 42, 33] },
  { id: 521,   name: 'Robert Lewandowski',      photo: IMG(521),   nationality: 'Poland',       age: 35, position: 'Attacker',   clubIds: [529, 157, 165] },
  { id: 521,   name: 'Dušan Vlahović',          photo: IMG(521),   nationality: 'Serbia',       age: 24, position: 'Attacker',   clubIds: [496, 497] },
  { id: 521,   name: 'Victor Osimhen',          photo: IMG(521),   nationality: 'Nigeria',      age: 25, position: 'Attacker',   clubIds: [492, 79] },
  { id: 521,   name: 'Ferran Torres',           photo: IMG(521),   nationality: 'Spain',        age: 24, position: 'Attacker',   clubIds: [529, 50] },
  { id: 521,   name: 'Julián Álvarez',          photo: IMG(521),   nationality: 'Argentina',    age: 24, position: 'Attacker',   clubIds: [50] },
  // ── Midfielders ──────────────────────────────────────────────────────────
  { id: 627,   name: 'Kevin De Bruyne',         photo: IMG(627),   nationality: 'Belgium',      age: 32, position: 'Midfielder', clubIds: [50, 49] },
  { id: 1485,  name: 'Pedri',                   photo: IMG(1485),  nationality: 'Spain',        age: 21, position: 'Midfielder', clubIds: [529] },
  { id: 19591, name: 'Jude Bellingham',         photo: IMG(19591), nationality: 'England',      age: 20, position: 'Midfielder', clubIds: [541, 165] },
  { id: 2931,  name: 'Rodri',                   photo: IMG(2931),  nationality: 'Spain',        age: 27, position: 'Midfielder', clubIds: [50, 73] },
  { id: 1485,  name: 'Frenkie de Jong',         photo: IMG(1485),  nationality: 'Netherlands',  age: 26, position: 'Midfielder', clubIds: [529, 194] },
  { id: 1485,  name: 'Bruno Fernandes',         photo: IMG(1485),  nationality: 'Portugal',     age: 29, position: 'Midfielder', clubIds: [33, 228] },
  { id: 521,   name: 'Phil Foden',              photo: IMG(521),   nationality: 'England',      age: 23, position: 'Midfielder', clubIds: [50] },
  { id: 521,   name: 'Jamal Musiala',           photo: IMG(521),   nationality: 'Germany',      age: 21, position: 'Midfielder', clubIds: [157] },
  { id: 521,   name: 'Gavi',                    photo: IMG(521),   nationality: 'Spain',        age: 19, position: 'Midfielder', clubIds: [529] },
  { id: 521,   name: 'Eduardo Camavinga',       photo: IMG(521),   nationality: 'France',       age: 21, position: 'Midfielder', clubIds: [541] },
  { id: 521,   name: 'Aurélien Tchouaméni',     photo: IMG(521),   nationality: 'France',       age: 23, position: 'Midfielder', clubIds: [541, 82] },
  { id: 521,   name: 'Paul Pogba',              photo: IMG(521),   nationality: 'France',       age: 30, position: 'Midfielder', clubIds: [496, 33] },
  { id: 521,   name: 'Toni Kroos',              photo: IMG(521),   nationality: 'Germany',      age: 34, position: 'Midfielder', clubIds: [541, 157] },
  { id: 521,   name: 'Luka Modrić',             photo: IMG(521),   nationality: 'Croatia',      age: 38, position: 'Midfielder', clubIds: [541, 47] },
  { id: 521,   name: 'Casemiro',                photo: IMG(521),   nationality: 'Brazil',       age: 31, position: 'Midfielder', clubIds: [33, 541] },
  { id: 521,   name: 'N\'Golo Kanté',           photo: IMG(521),   nationality: 'France',       age: 32, position: 'Midfielder', clubIds: [726, 49, 46] },
  { id: 521,   name: 'Christian Eriksen',       photo: IMG(521),   nationality: 'Denmark',      age: 31, position: 'Midfielder', clubIds: [33, 55, 505, 47] },
  { id: 521,   name: 'Mason Mount',             photo: IMG(521),   nationality: 'England',      age: 25, position: 'Midfielder', clubIds: [33, 49] },
  { id: 521,   name: 'Martin Ødegaard',         photo: IMG(521),   nationality: 'Norway',       age: 25, position: 'Midfielder', clubIds: [42, 541] },
  { id: 521,   name: 'Franck Kessié',           photo: IMG(521),   nationality: 'Ivory Coast',  age: 26, position: 'Midfielder', clubIds: [529, 489] },
  { id: 521,   name: 'Declan Rice',             photo: IMG(521),   nationality: 'England',      age: 25, position: 'Midfielder', clubIds: [42, 48] },
  { id: 521,   name: 'Alexis Mac Allister',     photo: IMG(521),   nationality: 'Argentina',    age: 25, position: 'Midfielder', clubIds: [40, 51] },
  { id: 521,   name: 'Dominik Szoboszlai',      photo: IMG(521),   nationality: 'Hungary',      age: 23, position: 'Midfielder', clubIds: [40, 167] },
  { id: 521,   name: 'Thomas Müller',           photo: IMG(521),   nationality: 'Germany',      age: 34, position: 'Midfielder', clubIds: [157] },
  { id: 521,   name: 'Xavi Simons',             photo: IMG(521),   nationality: 'Netherlands',  age: 21, position: 'Midfielder', clubIds: [165, 85, 529] },
  { id: 521,   name: 'Florian Wirtz',           photo: IMG(521),   nationality: 'Germany',      age: 21, position: 'Midfielder', clubIds: [168] },
  { id: 521,   name: 'Youri Tielemans',         photo: IMG(521),   nationality: 'Belgium',      age: 26, position: 'Midfielder', clubIds: [62, 46, 82] },
  { id: 521,   name: 'James Maddison',          photo: IMG(521),   nationality: 'England',      age: 27, position: 'Midfielder', clubIds: [47, 46] },
  { id: 521,   name: 'Federico Valverde',       photo: IMG(521),   nationality: 'Uruguay',      age: 25, position: 'Midfielder', clubIds: [541] },
  { id: 521,   name: 'İlkay Gündoğan',          photo: IMG(521),   nationality: 'Germany',      age: 33, position: 'Midfielder', clubIds: [529, 50, 165] },
  // ── Defenders ────────────────────────────────────────────────────────────
  { id: 521,   name: 'Virgil van Dijk',         photo: IMG(521),   nationality: 'Netherlands',  age: 32, position: 'Defender',   clubIds: [40, 41] },
  { id: 521,   name: 'Ruben Dias',              photo: IMG(521),   nationality: 'Portugal',     age: 26, position: 'Defender',   clubIds: [50, 211] },
  { id: 521,   name: 'Trent Alexander-Arnold',  photo: IMG(521),   nationality: 'England',      age: 25, position: 'Defender',   clubIds: [40] },
  { id: 521,   name: 'Alphonso Davies',         photo: IMG(521),   nationality: 'Canada',       age: 23, position: 'Defender',   clubIds: [157] },
  { id: 521,   name: 'Theo Hernández',          photo: IMG(521),   nationality: 'France',       age: 26, position: 'Defender',   clubIds: [489, 541] },
  { id: 521,   name: 'Achraf Hakimi',           photo: IMG(521),   nationality: 'Morocco',      age: 25, position: 'Defender',   clubIds: [85, 505, 541, 165] },
  { id: 521,   name: 'João Cancelo',            photo: IMG(521),   nationality: 'Portugal',     age: 29, position: 'Defender',   clubIds: [529, 50, 496, 505] },
  { id: 521,   name: 'Benjamin Pavard',         photo: IMG(521),   nationality: 'France',       age: 27, position: 'Defender',   clubIds: [505, 157] },
  { id: 521,   name: 'Raphaël Varane',          photo: IMG(521),   nationality: 'France',       age: 30, position: 'Defender',   clubIds: [33, 541] },
  { id: 521,   name: 'Jules Koundé',            photo: IMG(521),   nationality: 'France',       age: 25, position: 'Defender',   clubIds: [529, 536] },
  { id: 521,   name: 'Dayot Upamecano',         photo: IMG(521),   nationality: 'France',       age: 25, position: 'Defender',   clubIds: [157, 167] },
  { id: 521,   name: 'William Saliba',          photo: IMG(521),   nationality: 'France',       age: 22, position: 'Defender',   clubIds: [42, 81] },
  { id: 521,   name: 'Gabriel Magalhães',       photo: IMG(521),   nationality: 'Brazil',       age: 25, position: 'Defender',   clubIds: [42, 79] },
  { id: 521,   name: 'Reece James',             photo: IMG(521),   nationality: 'England',      age: 24, position: 'Defender',   clubIds: [49] },
  { id: 521,   name: 'Andrew Robertson',        photo: IMG(521),   nationality: 'Scotland',     age: 29, position: 'Defender',   clubIds: [40] },
  { id: 521,   name: 'Lisandro Martínez',       photo: IMG(521),   nationality: 'Argentina',    age: 26, position: 'Defender',   clubIds: [33, 194] },
  { id: 521,   name: 'Micky van de Ven',        photo: IMG(521),   nationality: 'Netherlands',  age: 22, position: 'Defender',   clubIds: [47] },
  { id: 521,   name: 'Ben White',               photo: IMG(521),   nationality: 'England',      age: 26, position: 'Defender',   clubIds: [42, 51] },
  { id: 521,   name: 'Pau Torres',              photo: IMG(521),   nationality: 'Spain',        age: 27, position: 'Defender',   clubIds: [62, 533] },
  { id: 521,   name: 'Antonio Rüdiger',         photo: IMG(521),   nationality: 'Germany',      age: 30, position: 'Defender',   clubIds: [541, 49, 488] },
  { id: 521,   name: 'David Alaba',             photo: IMG(521),   nationality: 'Austria',      age: 31, position: 'Defender',   clubIds: [541, 157] },
  { id: 521,   name: 'Lucas Hernández',         photo: IMG(521),   nationality: 'France',       age: 27, position: 'Defender',   clubIds: [85, 157, 73] },
  { id: 521,   name: 'Caglar Soyuncu',          photo: IMG(521),   nationality: 'Turkey',       age: 27, position: 'Defender',   clubIds: [62, 46] },
  { id: 521,   name: 'Kieran Trippier',         photo: IMG(521),   nationality: 'England',      age: 33, position: 'Defender',   clubIds: [34, 73, 47] },
  { id: 521,   name: 'Sergiño Dest',            photo: IMG(521),   nationality: 'USA',          age: 23, position: 'Defender',   clubIds: [529, 489, 194] },
  { id: 521,   name: 'Ferdi Kadioglu',          photo: IMG(521),   nationality: 'Netherlands',  age: 24, position: 'Defender',   clubIds: [40] },
  // ── Goalkeepers ──────────────────────────────────────────────────────────
  { id: 521,   name: 'Alisson',                 photo: IMG(521),   nationality: 'Brazil',       age: 31, position: 'Goalkeeper', clubIds: [40, 488] },
  { id: 521,   name: 'Thibaut Courtois',        photo: IMG(521),   nationality: 'Belgium',      age: 31, position: 'Goalkeeper', clubIds: [541, 49, 45] },
  { id: 521,   name: 'Ederson',                 photo: IMG(521),   nationality: 'Brazil',       age: 30, position: 'Goalkeeper', clubIds: [50, 211] },
  { id: 521,   name: 'Marc-André ter Stegen',   photo: IMG(521),   nationality: 'Germany',      age: 31, position: 'Goalkeeper', clubIds: [529] },
  { id: 521,   name: 'David de Gea',            photo: IMG(521),   nationality: 'Spain',        age: 33, position: 'Goalkeeper', clubIds: [33] },
  { id: 521,   name: 'Mike Maignan',            photo: IMG(521),   nationality: 'France',       age: 28, position: 'Goalkeeper', clubIds: [489, 79] },
  { id: 521,   name: 'Manuel Neuer',            photo: IMG(521),   nationality: 'Germany',      age: 37, position: 'Goalkeeper', clubIds: [157, 162] },
  { id: 521,   name: 'Gianluigi Donnarumma',    photo: IMG(521),   nationality: 'Italy',        age: 24, position: 'Goalkeeper', clubIds: [85, 489] },
  { id: 521,   name: 'André Onana',             photo: IMG(521),   nationality: 'Cameroon',     age: 27, position: 'Goalkeeper', clubIds: [33, 505, 194] },
  { id: 521,   name: 'Jordan Pickford',         photo: IMG(521),   nationality: 'England',      age: 30, position: 'Goalkeeper', clubIds: [45] },
  { id: 521,   name: 'Nick Pope',               photo: IMG(521),   nationality: 'England',      age: 31, position: 'Goalkeeper', clubIds: [34] },
  { id: 521,   name: 'David Raya',              photo: IMG(521),   nationality: 'Spain',        age: 28, position: 'Goalkeeper', clubIds: [42, 55] },
  { id: 521,   name: 'Gregor Kobel',            photo: IMG(521),   nationality: 'Switzerland',  age: 26, position: 'Goalkeeper', clubIds: [165] },
  { id: 521,   name: 'Yann Sommer',             photo: IMG(521),   nationality: 'Switzerland',  age: 35, position: 'Goalkeeper', clubIds: [505, 157, 163] },
  // ── Legends (for Footle / Connections / Grid historical) ─────────────────
  { id: 10001, name: 'Ronaldinho',              photo: IMG(521),   nationality: 'Brazil',       age: 43, position: 'Attacker',   clubIds: [529, 489, 85] },
  { id: 10002, name: 'Thierry Henry',           photo: IMG(521),   nationality: 'France',       age: 46, position: 'Attacker',   clubIds: [42, 541, 496] },
  { id: 10003, name: 'Zlatan Ibrahimovic',      photo: IMG(521),   nationality: 'Sweden',       age: 42, position: 'Attacker',   clubIds: [489, 85, 505, 33, 529, 496] },
  { id: 10004, name: 'Wayne Rooney',            photo: IMG(521),   nationality: 'England',      age: 38, position: 'Attacker',   clubIds: [33, 45] },
  { id: 10005, name: 'Didier Drogba',           photo: IMG(521),   nationality: 'Ivory Coast',  age: 46, position: 'Attacker',   clubIds: [49, 81] },
  { id: 10006, name: 'Fernando Torres',         photo: IMG(521),   nationality: 'Spain',        age: 40, position: 'Attacker',   clubIds: [49, 40, 73] },
  { id: 10007, name: 'David Beckham',           photo: IMG(521),   nationality: 'England',      age: 49, position: 'Midfielder', clubIds: [85, 33, 541] },
  { id: 10008, name: 'Andrés Iniesta',          photo: IMG(521),   nationality: 'Spain',        age: 39, position: 'Midfielder', clubIds: [529] },
  { id: 10009, name: 'Xavi Hernández',          photo: IMG(521),   nationality: 'Spain',        age: 44, position: 'Midfielder', clubIds: [529] },
  { id: 10010, name: 'Steven Gerrard',          photo: IMG(521),   nationality: 'England',      age: 43, position: 'Midfielder', clubIds: [40] },
  { id: 10011, name: 'Frank Lampard',           photo: IMG(521),   nationality: 'England',      age: 45, position: 'Midfielder', clubIds: [49, 33] },
  { id: 10012, name: 'Patrick Vieira',          photo: IMG(521),   nationality: 'France',       age: 47, position: 'Midfielder', clubIds: [42, 505, 496] },
  { id: 10013, name: 'Zinedine Zidane',         photo: IMG(521),   nationality: 'France',       age: 52, position: 'Midfielder', clubIds: [541, 496] },
  { id: 10014, name: 'Paul Scholes',            photo: IMG(521),   nationality: 'England',      age: 49, position: 'Midfielder', clubIds: [33] },
  { id: 10015, name: 'Roy Keane',               photo: IMG(521),   nationality: 'Ireland',      age: 52, position: 'Midfielder', clubIds: [33] },
  { id: 10016, name: 'John Terry',              photo: IMG(521),   nationality: 'England',      age: 43, position: 'Defender',   clubIds: [49, 62] },
  { id: 10017, name: 'Rio Ferdinand',           photo: IMG(521),   nationality: 'England',      age: 45, position: 'Defender',   clubIds: [33, 48] },
  { id: 10018, name: 'Nemanja Vidić',           photo: IMG(521),   nationality: 'Serbia',       age: 42, position: 'Defender',   clubIds: [33, 505] },
  { id: 10019, name: 'Paolo Maldini',           photo: IMG(521),   nationality: 'Italy',        age: 55, position: 'Defender',   clubIds: [489] },
  { id: 10020, name: 'Fabio Cannavaro',         photo: IMG(521),   nationality: 'Italy',        age: 50, position: 'Defender',   clubIds: [541, 496, 492] },
  { id: 10021, name: 'Roberto Carlos',          photo: IMG(521),   nationality: 'Brazil',       age: 51, position: 'Defender',   clubIds: [541] },
  { id: 10022, name: 'Carles Puyol',            photo: IMG(521),   nationality: 'Spain',        age: 45, position: 'Defender',   clubIds: [529] },
  { id: 10023, name: 'Peter Schmeichel',        photo: IMG(521),   nationality: 'Denmark',      age: 60, position: 'Goalkeeper', clubIds: [33] },
  { id: 10024, name: 'Gianluigi Buffon',        photo: IMG(521),   nationality: 'Italy',        age: 46, position: 'Goalkeeper', clubIds: [496, 85] },
  { id: 10025, name: 'Iker Casillas',           photo: IMG(521),   nationality: 'Spain',        age: 43, position: 'Goalkeeper', clubIds: [541, 212] },
]
